### ISSUE TITLE
能不能提供一个大运和流年排盘的示例呢？

### ISSUE THREAD

**Issue by coossss** [airicyu/fortel-ziweidoushu#1]
能不能提供一个大运和流年排盘的示例呢？

**Comment by airicyu** [comment]
@coossss 我剛更新了readme文檔, 你看看是否明白?

https://github.com/airicyu/fortel-ziweidoushu#runtime-context-%E5%A4%A7%E9%81%8B%E6%B5%81%E5%B9%B4%E6%B5%81%E6%9C%88%E6%B5%81%E6%97%A5%E8%B3%87%E8%A8%8A

主要就是用"getRuntimContext"這method就能得到大運/流年月日的資訊。

**Comment by coossss** [comment]
const runtimeContext = destinyBoard.getRuntimContext({
    lunarYear: 2023,
    lunarMonth: 5,
    lunarDay: 1,
    leap: 0,
})     这个leap 设置 false会报错，另外为什么	console.log(runtimeContext); 显示的是下面样式，为什么，"groundStars": {},
		"starDerivativeMap": {}没有数据呢？
{
	"age": 54,
	"day": {
		"cellGround": {
			"displayName": "寅",
			"index": 2
		},
		"groundStars": {},
		"starDerivativeMap": {}
	},
	"dayGround": {
		"displayName": "未",
		"index": 7
	},
	"daySky": {
		"displayName": "丁",
		"index": 3
	},
	"effectiveMonth": 5,
	"month": {
		"cellGround": {
			"displayName": "寅",
			"index": 2
		},
		"groundStars": {},
		"starDerivativeMap": {}
	},
	"monthGround": {
		"displayName": "午",
		"index": 6
	},
	"monthSky": {
		"displayName": "戊",
		"index": 4
	},
	"tenYear": {
		"cellGround": {
			"displayName": "亥",
			"index": 11
		},
		"groundStars": {},
		"starDerivativeMap": {}
	},
	"tenYearGround": {
		"displayName": "亥",
		"index": 11
	},
	"tenYearSky": {
		"displayName": "丁",
		"index": 3
	},
	"year": {
		"cellGround": {
			"displayName": "卯",
			"index": 3
		},
		"groundStars": {},
		"starDerivativeMap": {}
	},
	"yearGround": {
		"displayName": "卯",
		"index": 3
	},
	"yearSky": {
		"displayName": "癸",
		"index": 9
	}
}
能否提供个完整的"getRuntimContext"显示大運/流年月日的資訊的代码示例？

**Comment by airicyu** [comment]
import { DestinyBoard, DestinyConfigBuilder, DayTimeGround, ConfigType, Gender } from '.....'

const destinyBoard = new DestinyBoard(
    DestinyConfigBuilder.withlunar({
        year: 1952, // 年
        month: 3, //月
        day: 15, //日
        isLeapMonth: false, // 非潤月
        bornTimeGround: DayTimeGround.getByName('寅時'), // 出生時辰
        configType: ConfigType.SKY, // 天盤, if missing this option, default is 天盤
        gender: Gender.F, // 女士
    }),
)

const runtimeContext = destinyBoard.getRuntimContext({
    lunarYear: 2023,
    lunarMonth: 5,
    lunarDay: 1,
    leap: false,
})

我這個能運行到, 你pass leap=false報的錯是什麼?
你pass leap=false報錯的, DestinyBoard的設定是什麼盤? 

你看那個runtimeContext的type的話, groundStars, starDerivativeMap不是object, 而是js的Map, console.log會print不出來。
你可以試試弄個breakpoint去debug, 就能看到。

**Comment by airicyu** [comment]
我先close了這個issue吧，有問題可以隨時再問下，thx~
